[package]
name = "photo_meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
kamadak-exif = "0.5.5"
rfd = "0.11.4"
plotters = "0.3.3"
log = "0.4"
walkdir = "2.3.2"
